# Custom Resource Definition for an Anvil.
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: anvils.acme.com
spec:
  group: acme.com
  version: v1
  scope: Namespaced
  names:
    plural: anvils
    singular: anvil
    kind: Anvil
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - lbs
          properties:
            lbs:
              type: integer
              minimum: 1
              maximum: 9000
